(() => {
  const ROOT_ID = "xca-root";
  const POSITION_KEY = "xca-floating-position";
  const DEFAULT_PERSONA = "practical operator, curious builder, concise and natural";
  const DEFAULT_COUNT = 5;
  const DEFAULT_MAX_CHARS = 220;

  if (document.getElementById(ROOT_ID)) {
    return;
  }

  const root = document.createElement("div");
  root.id = ROOT_ID;
  root.className = "xca-root";
  root.innerHTML = `
    <button class="xca-toggle" type="button" title="Open Reply Assistant"><span>AI</span><strong>Reply</strong></button>
    <section class="xca-panel xca-hidden" aria-label="X Comment Agent">
      <div class="xca-head">
        <h2 class="xca-title">Reply Assistant</h2>
        <button class="xca-close" type="button" aria-label="Close">×</button>
      </div>
      <div class="xca-body">
        <details class="xca-source">
          <summary>Context note</summary>
          <textarea class="xca-textarea" data-role="context-note" placeholder="Optional: describe images, charts, sarcasm, or background you want the model to consider."></textarea>
        </details>
        <div class="xca-toolbar">
          <button class="xca-button primary" type="button" data-action="generate">Generate Reply</button>
          <button class="xca-button" type="button" data-action="console">Open Control Panel</button>
        </div>
        <p class="xca-status" role="status"></p>
        <div class="xca-list"></div>
      </div>
    </section>
  `;
  document.documentElement.appendChild(root);

  const toggle = root.querySelector(".xca-toggle");
  const panel = root.querySelector(".xca-panel");
  const close = root.querySelector(".xca-close");
  const status = root.querySelector(".xca-status");
  const list = root.querySelector(".xca-list");
  const generateButton = root.querySelector('[data-action="generate"]');
  const contextNote = root.querySelector('[data-role="context-note"]');
  let didDrag = false;

  restoreFloatingPosition();
  enableDrag();

  toggle.addEventListener("click", () => {
    if (didDrag) {
      didDrag = false;
      return;
    }
    setOpen(true);
  });
  close.addEventListener("click", () => setOpen(false));

  root.querySelector('[data-action="console"]').addEventListener("click", async () => {
    try {
      const response = await chrome.runtime.sendMessage({ type: "XCA_CONTROL_PANEL" });
      const url = response && response.payload && response.payload.url ? response.payload.url : "http://192.168.31.188:8765/";
      window.open(url, "_blank", "noopener,noreferrer");
    } catch (_error) {
      window.open("http://192.168.31.188:8765/", "_blank", "noopener,noreferrer");
    }
  });

  generateButton.addEventListener("click", () => {
    const source = readCurrentTweet();
    if (!source.text) {
      setStatus("Could not identify the current tweet. Select the text and try Generate Reply.", true);
      return;
    }
    generateFromSource(source);
  });

  async function generateFromSource(source) {
    generateButton.disabled = true;
    setStatus("Generating with DeepSeek...");
    list.innerHTML = "";

    const payload = {
      tweet: source.text,
      context: source.context || "",
      timeline_context: source.timelineContext || "",
      image_context: [source.imageContext || "", contextNote.value.trim()].filter(Boolean).join("\n"),
      post_time: source.postTime || "",
      page_url: location.href,
      persona: DEFAULT_PERSONA,
      language: "auto",
      style: "adaptive",
      count: DEFAULT_COUNT,
      max_chars: DEFAULT_MAX_CHARS,
      use_llm: true
    };

    try {
      const response = await chrome.runtime.sendMessage({ type: "XCA_GENERATE", payload });
      if (!response || !response.ok) {
        throw new Error((response && response.error) || "Generation failed.");
      }
      const candidates = response.payload.candidates || [];
      renderCandidates(candidates);
      const provider = response.payload.provider || "agent";
      const language = response.payload.language === "zh" ? "Chinese" : "English";
      const warning = response.payload.warning ? " Fallback rules used." : "";
      setStatus(`${candidates.length} ${language} replies generated by ${provider}.${warning}`);
    } catch (error) {
      setStatus(error.message || "Generation failed.", true);
    } finally {
      generateButton.disabled = false;
    }
  }

  function setOpen(open) {
    panel.classList.toggle("xca-hidden", !open);
    if (open) {
      positionPanelNearToggle();
    }
  }

  function enableDrag() {
    let startX = 0;
    let startY = 0;
    let startLeft = 0;
    let startTop = 0;
    let dragging = false;

    toggle.addEventListener("mousedown", (event) => {
      if (event.button !== 0) {
        return;
      }
      const rect = toggle.getBoundingClientRect();
      startX = event.clientX;
      startY = event.clientY;
      startLeft = rect.left;
      startTop = rect.top;
      dragging = true;
      didDrag = false;
      toggle.classList.add("dragging");
      event.preventDefault();
    });

    window.addEventListener("mousemove", (event) => {
      if (!dragging) {
        return;
      }
      const dx = event.clientX - startX;
      const dy = event.clientY - startY;
      if (Math.abs(dx) > 3 || Math.abs(dy) > 3) {
        didDrag = true;
      }
      setFloatingPosition(startLeft + dx, startTop + dy, false);
    });

    window.addEventListener("mouseup", () => {
      if (!dragging) {
        return;
      }
      dragging = false;
      toggle.classList.remove("dragging");
      saveFloatingPosition();
      setTimeout(() => {
        didDrag = false;
      }, 120);
    });

    window.addEventListener("resize", () => {
      const rect = toggle.getBoundingClientRect();
      setFloatingPosition(rect.left, rect.top, true);
      saveFloatingPosition();
    });
  }

  function restoreFloatingPosition() {
    try {
      const raw = localStorage.getItem(POSITION_KEY);
      if (!raw) {
        positionPanelNearToggle();
        return;
      }
      const position = JSON.parse(raw);
      setFloatingPosition(Number(position.left), Number(position.top), true);
    } catch (_error) {
      positionPanelNearToggle();
    }
  }

  function saveFloatingPosition() {
    const rect = toggle.getBoundingClientRect();
    localStorage.setItem(POSITION_KEY, JSON.stringify({ left: Math.round(rect.left), top: Math.round(rect.top) }));
  }

  function setFloatingPosition(left, top, clamp) {
    const width = toggle.offsetWidth || 92;
    const height = toggle.offsetHeight || 40;
    let nextLeft = Number.isFinite(left) ? left : window.innerWidth - width - 18;
    let nextTop = Number.isFinite(top) ? top : 112;
    if (clamp !== false) {
      nextLeft = Math.max(8, Math.min(nextLeft, window.innerWidth - width - 8));
      nextTop = Math.max(8, Math.min(nextTop, window.innerHeight - height - 8));
    }
    toggle.style.left = `${nextLeft}px`;
    toggle.style.top = `${nextTop}px`;
    toggle.style.right = "auto";
    positionPanelNearToggle();
  }

  function positionPanelNearToggle() {
    const rect = toggle.getBoundingClientRect();
    const panelWidth = Math.min(410, window.innerWidth - 28);
    const left = Math.max(10, Math.min(rect.left, window.innerWidth - panelWidth - 10));
    const below = rect.bottom + 8;
    const top = below + 260 < window.innerHeight ? below : Math.max(10, rect.top - 12);
    panel.style.left = `${left}px`;
    panel.style.top = `${top}px`;
    panel.style.right = "auto";
  }

  function readCurrentTweet() {
    const selection = window.getSelection();
    const selected = String(selection ? selection.toString() : "").trim();
    if (selected && selected.length >= 12) {
      return {
        text: cleanText(selected),
        context: "",
        timelineContext: buildTimelineContext(),
        imageContext: "",
        postTime: "",
      };
    }

    const statusId = getStatusId();
    const articles = Array.from(document.querySelectorAll('article[data-testid="tweet"]'));
    const candidates = [];

    for (const article of articles) {
      const tweetText = article.querySelector('[data-testid="tweetText"]');
      const text = cleanText(tweetText ? tweetText.innerText : "");
      if (!text) {
        continue;
      }
      const links = Array.from(article.querySelectorAll('a[href*="/status/"]')).map((link) => link.getAttribute("href") || "");
      const hasStatus = statusId ? links.some((href) => href.includes(`/status/${statusId}`)) : false;
      const rect = article.getBoundingClientRect();
      const meta = readArticleMeta(article);
      candidates.push({
        index: articles.indexOf(article),
        text,
        hasStatus,
        topDistance: Math.abs(rect.top),
        length: text.length,
        postTime: meta.postTime,
        imageContext: meta.imageContext
      });
    }

    if (!candidates.length) {
      return { text: "", context: "" };
    }

    candidates.sort((a, b) => {
      if (a.hasStatus !== b.hasStatus) {
        return a.hasStatus ? -1 : 1;
      }
      return a.topDistance - b.topDistance || b.length - a.length;
    });

    const target = candidates[0];
    return {
      text: target.text,
      context: buildThreadContext(articles, target.index),
      timelineContext: buildTimelineContext(articles),
      imageContext: target.imageContext,
      postTime: target.postTime
    };
  }

  function buildThreadContext(articles, targetIndex) {
    if (targetIndex <= 0) {
      return "";
    }
    const previous = articles
      .slice(Math.max(0, targetIndex - 4), targetIndex)
      .map((article) => {
        const tweetText = article.querySelector('[data-testid="tweetText"]');
        const text = cleanText(tweetText ? tweetText.innerText : "");
        const meta = readArticleMeta(article);
        return [meta.postTime ? `Time: ${meta.postTime}` : "", text].filter(Boolean).join(" | ");
      })
      .filter(Boolean);

    return previous.map((text, index) => `Context ${index + 1}: ${text}`).join("\n");
  }

  function buildTimelineContext(articles = Array.from(document.querySelectorAll('article[data-testid="tweet"]'))) {
    return articles
      .slice(0, 8)
      .map((article, index) => {
        const tweetText = article.querySelector('[data-testid="tweetText"]');
        const text = cleanText(tweetText ? tweetText.innerText : "");
        if (!text) {
          return "";
        }
        const meta = readArticleMeta(article);
        const imagePart = meta.imageContext ? ` Images: ${meta.imageContext}` : "";
        const timePart = meta.postTime ? ` Time: ${meta.postTime}` : "";
        return `Visible post ${index + 1}:${timePart} ${text}${imagePart}`.trim();
      })
      .filter(Boolean)
      .join("\n");
  }

  function readArticleMeta(article) {
    const timeNode = article.querySelector("time");
    const postTime = cleanText(timeNode ? timeNode.getAttribute("datetime") || timeNode.innerText || "" : "");
    const imageDescriptions = Array.from(article.querySelectorAll('img[alt], [aria-label]'))
      .map((node) => cleanText(node.getAttribute("alt") || node.getAttribute("aria-label") || ""))
      .filter((text) => text && !/^(image|avatar|profile|emoji)$/i.test(text))
      .slice(0, 6);
    return {
      postTime,
      imageContext: imageDescriptions.length ? imageDescriptions.map((text, index) => `Image ${index + 1}: ${text}`).join("; ") : ""
    };
  }

  function getStatusId() {
    const match = location.pathname.match(/\/status\/(\d+)/);
    return match ? match[1] : "";
  }

  function cleanText(text) {
    return String(text || "")
      .replace(/\s+\n/g, "\n")
      .replace(/\n\s+/g, "\n")
      .replace(/[ \t]{2,}/g, " ")
      .trim();
  }

  function renderCandidates(candidates) {
    list.innerHTML = "";
    if (!candidates.length) {
      list.innerHTML = '<p class="xca-status">No candidates returned.</p>';
      return;
    }

    for (const candidate of candidates) {
      const card = document.createElement("article");
      card.className = "xca-card";

      const top = document.createElement("div");
      top.className = "xca-card-top";

      const badges = document.createElement("div");
      badges.className = "xca-badges";
      badges.appendChild(makeBadge(candidate.angle || "reply"));

      const copy = document.createElement("button");
      copy.className = "xca-button";
      copy.type = "button";
      copy.textContent = "Copy";
      copy.addEventListener("click", async () => {
        await navigator.clipboard.writeText(candidate.text || "");
        copy.textContent = "Copied";
        setTimeout(() => {
          copy.textContent = "Copy";
        }, 1100);
      });

      const text = document.createElement("p");
      text.className = "xca-card-text";
      text.textContent = candidate.text || "";

      top.appendChild(badges);
      top.appendChild(copy);
      card.appendChild(top);
      card.appendChild(text);
      if (candidate.translation) {
        const translation = document.createElement("p");
        translation.className = "xca-card-translation";
        translation.textContent = `中文释义：${candidate.translation}`;
        card.appendChild(translation);
      }
      list.appendChild(card);
    }
  }

  function makeBadge(text) {
    const badge = document.createElement("span");
    badge.className = "xca-badge";
    badge.textContent = text;
    return badge;
  }

  function setStatus(message, isError = false) {
    status.textContent = message || "";
    status.classList.toggle("error", Boolean(isError));
  }
})();
